before_script:          # install the virtual environment
  - pipenv install --dev --pre
  - pipenv run which python

stages:
  - dep-check
  - quality
  - test
  - code-coverage

pipenv-install:
  stage: dep-check
  script:
    - pipenv check

flake8:
  stage: quality
  script:
    - pipenv run flake8

black:
  stage: quality
  script:
    - pipenv run black

mypy:
  stage: quality
  script:
    - echo TODO

test:
  stage: test
  script:
    - pipenv run pytest pymint/

test-code-coverage:
  stage: code-coverage
  script:
    - echo TODO
